### ISSUE TITLE
Katselmointi

### ISSUE THREAD

**Issue by Kaltsoon** [OlliJ5/PickupGameFinder#1]
# Katselmointi

Terve @OlliJ5! Tässä lyhyt katselmointi Full Stack kurssin projektistasi.

### Mitä tein?

- Rekisteröin uuden käyttäjän
- Tsekkasin profiilitietoni ja vaihdoin ulkoasun väriteeman
- Lisäsin uuden pelin
- Kirjauduin ulos
- Rekisteröin toisen käyttäjän ja liityin luomaani peliin
- Kirjauduin ulos

### Kokemus

- Selkeä ja tyylikäs käyttöliittymä, hyvää työtä! 🥇
- Uuden käyttäjän opasteet rekisteröitymisen jälkeen tekevät sovelluksen käytöstä helppoa
- Käyttöliittymä taipuu melko hyvin myös kapeammille näytöille, paitsi jostain syystä navigaatiopalkin oikean laidan käyttäjävalikko ei ole kapealla näytöllä enää näkyvissä
- Väriteeman (light/dark) vaihtaminen on loistava toiminallisuus
- Lomakkeissa on virhetilanteissa selkeät virheviestit

## Koodi

- Frontend-puolen koodi on selkeästi organisoitua, hyvä!
- Väriteemaan liittyvä konfiguraatio kannattaisi toteuttaa [css-muuttujina](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties), tai vaihtoehtoisesti käyttää jotain CSS-in-JS kirjastoa teema-konfiguraation kanssa, kuten [styled-components](https://styled-components.com/)
- Inline-tyylejä, eli tyylien määrittelemistä `style`-propin avulla kannattaa välttää. Määrittele sen sijaan tyylit css-tiedostossa käyttämällä esim. luokkavalitsinta ja `className`-propsia
- Hyvä idea käyttää Formikia lomakkeiden tilanhallinnassa
- Syvien tietorakenteiden immutable päivittäminen Reduxin reducereissa puhtaalla JavaScriptilla on melko työlästä. [Immer](https://www.npmjs.com/package/immer)-kirjasto helpottaa tätä huomattavasti
- [Redux Toolkit](https://redux-toolkit.js.org/) tarjoaa todella hyviä työkaluja Reduxin käyttöön. Esim. [createReducer](https://redux-toolkit.js.org/usage/usage-with-typescript#createreducer)-funktio vähentää reducerien boilerplate koodia huomattavasti. Se käyttää sisäisesti Immer-kirjastoa, joten myös tilan päivittäminen helpottuu
- Frontendissä on hyvänoloinen CI-putki
- Myös backend-puolen koodi on selkeästi organisoitua, hienoa!
- Reittien käsittelijöiden ainaisista `try { ... } catch (e) { next(e) }`-lohkoista pääsee helposti eroon [express-async-errors](https://www.npmjs.com/package/express-async-errors)-kirjaston avulla
- Autentikaatiotokenin verifioinnin voisi siirtää omaan middlewareensa. Tällä hetkellä näihin operaatioihin liittyvää koodia on duplikoitu monessa reitin käsittelijässä

## Kokonaisuus

- Hyödyllinen ja käyttäjäystävällinen sovellus, josta ei puutu mitään olennaista toiminallisuutta
- Koodi on kaikilta osin järkevästi organisoitua ja helppolukuista, eikä mitään pahemmanlaatuisia koodihajuja löytynyt

**Comment by OlliJ5** [comment]
Kiitos kommenteista, näistä varmasti hyötyä tulevissa projekteissa!
